### ISSUE TITLE
Unhandled case org.freedesktop.appearance.color-scheme=0 breaks plug-in function

### ISSUE THREAD

**Issue by davidfoerster** [smac89/autodark-sublime-plugin#1]
### Runtime environment
 * AutoDarkLinux (master, 7365279e61ca437edbfeaa94e44bdb6d8a826500)
 * Sublime Text 4 (build 4180)
 * GNOME Shell 47 (on Arch Linux)

### Expected behaviour
When operating in "system" mode, AutoDarkLinux enables/disables the dark mode of Sublime Text according to GNOME's dark mode.

### Actual behaviour
When AutoDarkLinux operates in "system" mode and...
 * GNOME's colours are already in default (light) mode, Sublime Texts is set to (or remains in) dark mode.
 * GNOME's changes from dark to default (light) mode, sometimes AutoDarkLinux crashes altogether or Sublime Text freezes until SIGKILL.

### Suspected underlying issue
The theme switcher built into GNOME Shell swaps the value of `org.freedesktop.appearance.color-scheme` between 1 (prefer dark) and 0 (default colours, typically a light) but AutoDark doesn't handle the latter case at all. The Freedesktop specification doesn't assign any preference to value 0 (=default) but it would be nice to at least fail gracefully.

In a quick hack I mapped value 0 to AutoDark's "light" mode and now it operates as expected in GNOME. I'll clean that up an submit a pull request soon.

---

P. S.: Thanks for the useful plug-in to work around a Sublime Text defect!

**Comment by smac89** [comment]
Thanks for the information.

I'm actually curious about the crash. Could you run the plugin in debug mode (see https://github.com/smac89/autodark-sublime-plugin/blob/7365279e61ca437edbfeaa94e44bdb6d8a826500/AutoDarkLinux.sublime-settings#L3), and include any logs you see from the console.

To open and enable logging in the console, see number **3** in https://github.com/smac89/autodark-sublime-plugin?tab=readme-ov-file#development.

As for the inconsistent behaviour of gnome, I will take a look this weekend.

**Comment by rubin55** [comment]
I have the exact same issue. Enabling logging, I'm seeing this in the console, when I click on the Gnome "Dark Style" toggle:

```
Exception in thread AutoDarkLinuxMonitor:
Traceback (most recent call last):
  File "./python3.8/threading.py", line 932, in _bootstrap_inner
  File "./python3.8/threading.py", line 870, in run
  File "/home/rubin/.config/sublime-text/Installed Packages/AutoDarkLinux.sublime-package/main.py", line 151, in monitor
  File "/home/rubin/.config/sublime-text/Installed Packages/AutoDarkLinux.sublime-package/helpers.py", line 59, in parse_dbus_monitor
KeyError: 0
```
